### ISSUE TITLE
Unknown Cuda Error when running the GUI

### ISSUE THREAD

**Issue by WangDeyao** [VLOGroup/dvs-reconstruction#11]
Hi,

I got a Cuda error when running the GUI. After I load the sample data and hit play, the GUI terminated. Here is everything I got from the terminal after I run live_reconstruction_gui:

XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
CUDA error: cudaErrorUnknown:unknown error
 File: /home/SENSETIME/wangdaoye/PycharmProjects/event-deblur/others_code/dvs-reconstruction/imageutilities/src/iugui/qt5imagegpuwidget.cpp
 Function: init_cuda
 Line: 163
CUDA error: cudaErrorUnknown:unknown error
 File: /home/SENSETIME/wangdaoye/PycharmProjects/event-deblur/others_code/dvs-reconstruction/imageutilities/src/iugui/qt5imagegpuwidget.cpp
 Function: init_cuda
 Line: 163
CUDA error: cudaErrorUnknown:unknown error
 File: /home/SENSETIME/wangdaoye/PycharmProjects/event-deblur/others_code/dvs-reconstruction/imageutilities/src/iugui/qt5imagegpuwidget.cpp
 Function: init_cuda
 Line: 163
OpenGL profile: Core
OpenGL version: 3.3
Swap behaviour: 2
Render type: 1
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
terminate called after throwing an instance of 'IuCudaException'
  what():  IuException: CUDA Error: unknown error
      where: /home/SENSETIME/wangdaoye/PycharmProjects/event-deblur/others_code/dvs-reconstruction/imageutilities/src/iucore/image_allocator_gpu.h | copy:34
Aborted (core dumped)

I wonder what's going wrong. Thanks!!

**Comment by reini1305** [comment]
Hi! Can you give me some details about your setup, like OS, graphics card and driver version?
Can you run any other GPU code?
The output of the `nvidia-smi` tool would also be helpful!

**Comment by WangDeyao** [comment]
Here is my setup. I am using Ubuntu 16.04, GTX1080Ti, Driver version 384.130, Cuda 9.0.

The output of nvidia-smi:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0  On |                  N/A |
|  8%   47C    P8    20W / 250W |    823MiB / 11169MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1320      G   /usr/lib/xorg/Xorg                           431MiB |
|    0      2545      G   compiz                                       190MiB |
|    0      4951      G   ...-token=743633EE45C3EC4C0291739561D466CB    53MiB |
|    0     11412      G   ...quest-channel-token=7539739204210641263   121MiB |
|    0     14545      G   .../local/MATLAB/R2015a/bin/glnxa64/MATLAB     4MiB |
|    0     20465      G   /opt/teamviewer/tv_bin/TeamViewer             19MiB |
+-----------------------------------------------------------------------------+

Thanks!

**Comment by reini1305** [comment]
I managed to compile and run everything on a (relatively) similar setup. Ubuntu 18.04, Cuda 10, Driver 410. Can you run `make test` in imageutilities?
