### ISSUE TITLE
Unable to launch live_reconstruction_gui

### ISSUE THREAD

**Issue by shixiaopei** [VLOGroup/dvs-reconstruction#12]
Hi,
I build and install all dependencies and finally build src as well, according to the README. I encountered the same problem as #8. I am unable to launch the live_reconstruction_gui. It shows the following error:

QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QOpenGLWidget: Failed to create context
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QOpenGLWidget: Failed to create context
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QOpenGLWidget: Failed to create context
composeAndFlush: makeCurrent() failed

We use NVIDIA-SMI 410.78 on Ubuntu 16.04. I'm using Qt version 5.12.0 and CUDA version 10.0.
We are working on the same problem and wanted to compare results. I learned from #8 that you have published an offline evaluation script. I also generated the file of'offline_reconstruction_XXX' in the build folder after following the README operation.

I would like to ask you how to input a dataset and run the offline evaluation script to generate reconstructed event images?
Could you help me resolve this issue? Thanks

**Comment by shixiaopei** [comment]
We tried to run'offline_reconstruction' in the generated build folder and learned how to use the offline evaluation script from the help file. Thank you for adding the offline evaluation script.

**Comment by reini1305** [comment]
Hi! Sorry to hear that the GUI doesn't work for you. I have now a Ubuntu 20.04 machine and try to get it running again and reproduce your problem.
Feel free to ask any questions you have regarding the offline evaluation script!

**Comment by shixiaopei** [comment]
Thank you for your reply. The help document you specified is very clear, and we have successfully run the offline evaluation script.
Thanks again
