### ISSUE TITLE
How to use offline_reconstruction for rosbags ?

### ISSUE THREAD

**Issue by vigneshkgith** [VLOGroup/dvs-reconstruction#13]
I have successfully installed the offline reconstruction as well as the live reconstruction gui ... I ran the offline reconstruction code with sample data (aer2 files) that were provided. It gave me a successful reconstruction... How do I use the same for event data which I have in the form of .bag files?.. Directly passing it as -f argument doesn't work... Thanks

**Comment by reini1305** [comment]
The file format is documented in the "Usage" section of the Readme file. You'd need to convert your data to this text format.

**Comment by vigneshkgith** [comment]
Ok thank you :)
