### ISSUE TITLE
Offline Reconstruction on GPU

### ISSUE THREAD

**Issue by satabios** [VLOGroup/dvs-reconstruction#14]
I've successfully built the dvs-reconstruction, and also I'm able to run offline_reconstruction on the CPU. At times when the .aer2 file is of a huge chunk it either runs out of memory or hangs the whole system. Due to which I was trying it to run it on GPU with the flag -g. My command looks like  `./offline_reconstruction -f  "event-based.aer2 file" -o "output_folder" -g`
The command throws an error:

`terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_command_line_syntax> >'
  what():  the required argument for option '--gpu' is missing
Aborted (core dumped)`

**Comment by reini1305** [comment]
offline_reconstruction only works with a GPU, so I'm not sure how you managed to run it with CPU alone. The `--gpu` switch only allows you to specify which GPU to use and therefore expects a number as additional input: e.g. `--gpu 0`
