### ISSUE TITLE
problem compiling the example

### ISSUE THREAD

**Issue by federicohyo** [VLOGroup/dvs-reconstruction#2]
Hi there!

thank you very much for sharing this code. I am Federico and I work at IniLabs GmbH, we produce and sell the neuromorphic vision sensors.

I am now trying to compile your code, however I am getting the following error, do you have any ideas on how to solve this? 

thank you very much for your support. I look forward seeing the intensity reconstruction in live action.

attached the log  

[  6%] Automatic moc for target live_reconstruction_gui
[  6%] Built target live_reconstruction_gui_automoc
[ 13%] Automatic moc for target common
[ 13%] Built target common_automoc
[ 46%] Built target common
[ 53%] Linking CXX executable live_reconstruction_gui
Running ld for x86_64 ...
Undefined symbols for architecture x86_64:
  "iu::Qt5ImageGpuWidget::Qt5ImageGpuWidget(iu::Size<2u>, QWidget*)", referenced from:
      ReconstructionMainWindow::ReconstructionMainWindow(QWidget*, std::__1::vector<Event, std::__1::allocator<Event> >&) in reconstructionmainwindow.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [live_reconstruction_gui] Error 1
make[1]: *** [CMakeFiles/live_reconstruction_gui.dir/all] Error 2
make: *** [all] Error 2

**Comment by reini1305** [comment]
Hi! Did you manage to build the `imageutilities` with the `iugui` module? Before you edited your comment, you had a compiler error on that one IIRC. Seems like it can't link `iugui`. What is your system configuration?

**Comment by federicohyo** [comment]
Hi, thank you for your quick reply.

My current configuration is Ubuntu 16.04, gcc 4.9 and I cannot compile imageutils, I have CUDA 7.5 and an NVIDIA GPU.

Here is the log when I try to build imageutilities.

 federico@zfractal:/media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/build$ make
[  1%] Automatic moc for target iugui
[  1%] Built target iugui_automoc
[  3%] Building CXX object src/CMakeFiles/iugui.dir/iugui/qt5imagegpuwidget.cpp.o
In file included from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:1:0:
/media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.h:20:1: error: expected class-name before ‘{’ token
 {
 ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/GL/glu.h:38,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:2:
/usr/local/cuda-7.5/samples/common/inc/GL/glext.h:6815:100: error: conflicting declaration ‘typedef void (\* PFNGLGETQUERYOBJECTI64VEXTPROC)(GLuint, GLenum, GLint64EXT_)’
 typedef void (APIENTRYP PFNGLGETQUERYOBJECTI64VEXTPROC)(GLuint id, GLenum pname, GLint64EXT *params);
                                                                                                    ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qopengl.h:110:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qopenglwidget.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QOpenGLWidget:1,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.h:3,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qopengles2ext.h:846:28: note: previous declaration as ‘typedef void (_ PFNGLGETQUERYOBJECTI64VEXTPROC)(GLuint, GLenum, GLint64_)’
 typedef void (GL_APIENTRYP PFNGLGETQUERYOBJECTI64VEXTPROC) (GLuint id, GLenum pname, GLint64 *params);
                            ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/GL/glu.h:38,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:2:
/usr/local/cuda-7.5/samples/common/inc/GL/glext.h:6816:102: error: conflicting declaration ‘typedef void (_ PFNGLGETQUERYOBJECTUI64VEXTPROC)(GLuint, GLenum, GLuint64EXT_)’
 typedef void (APIENTRYP PFNGLGETQUERYOBJECTUI64VEXTPROC)(GLuint id, GLenum pname, GLuint64EXT *params);
                                                                                                      ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qopengl.h:110:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qopenglwidget.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QOpenGLWidget:1,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.h:3,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qopengles2ext.h:847:28: note: previous declaration as ‘typedef void (_ PFNGLGETQUERYOBJECTUI64VEXTPROC)(GLuint, GLenum, GLuint64_)’
 typedef void (GL_APIENTRYP PFNGLGETQUERYOBJECTUI64VEXTPROC) (GLuint id, GLenum pname, GLuint64 *params);
                            ^
/media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp: In member function ‘virtual void iu::Qt5ImageGpuWidget::initializeGL()’:
/media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:169:31: error: ‘initializeOpenGLFunctions’ was not declared in this scope
     initializeOpenGLFunctions();   // initialize the QOpenGLFunctions_x_x
                               ^
src/CMakeFiles/iugui.dir/build.make:1154: recipe for target 'src/CMakeFiles/iugui.dir/iugui/qt5imagegpuwidget.cpp.o' failed
make[2]: *_\* [src/CMakeFiles/iugui.dir/iugui/qt5imagegpuwidget.cpp.o] Error 1
CMakeFiles/Makefile2:98: recipe for target 'src/CMakeFiles/iugui.dir/all' failed
make[1]: **\* [src/CMakeFiles/iugui.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by reini1305** [comment]
This issue is a direct consequence of https://github.com/VLOGroup/imageutilities/issues/1 so I'll close this one here for now.

**Comment by federicohyo** [comment]
Hi!
I am now running the code, pretty neat! 

Thank you for sharing.
