### ISSUE TITLE
libcaer.so.2 not found

### ISSUE THREAD

**Issue by raymond00000** [VLOGroup/dvs-reconstruction#3]
I followed the step and I can build it. but i got below error:

git clone --recursive https://github.com/VLOGroup/dvs-reconstruction

cd cnpy
cmake .
make
sudo make install
cd ../libcaer
cmake .
make
sudo make install

i got:
..
..
-- Up-to-date: /usr/local/lib/libcaer.so.2
-- Up-to-date: /usr/local/lib/libcaer.so

cd ..
mkdir build
cd build
cmake ../src
make -j6

But when i tried to run the bin, i got below error.

raymond@ubuntu1:~/dvs/dvs-reconstruction/build$ ./live_reconstruction_gui
./live_reconstruction_gui: error while loading shared libraries: libcaer.so.2: cannot open shared object file: No such file or directory

I guess i should not use sudo install??  No idea on how to fix the problem now..
Thanks for advice.

**Comment by reini1305** [comment]
Looks like `/usr/local/lib` is not on your library path. One possible (temporary) fix would be to launch the application with: `LD_LIBRARY_PATH=/usr/local/lib ./live_reconstruction_gui`

**Comment by raymond00000** [comment]
yes, i tried this way:

cp /usr/local/lib/libcnpy.so libcnpy.so
 cp /usr/local/lib/libcaer.so.2 libcaer.so.2

and also i tried this too:
LD_LIBRARY_PATH=/usr/local/lib ./live_reconstruction_gui

It should work. Many thanks for instant support! =)
