### ISSUE TITLE
the suggested config to try this project?

### ISSUE THREAD

**Issue by raymond00000** [VLOGroup/dvs-reconstruction#5]
HI, 

I spended few weeks but still I cannot install IMAGEUTILITIES.
I decide to start everything from scratch again.
Can you recommend the ubuntu version, openCV version, cuda version, that proved be working config for install this project?

Thanks.

**Comment by reini1305** [comment]
Hi,
I'm sorry to hear that, ususally Imageutilities should be much easier to install. We are using 14.04 and 16.04 with OpenCV 3.x (some installed it from source, but you can also use the built-in version of 16.04, the one of 14.04 is too old), CMake 3.2 or bigger.

The problem with your machine seems to be that OpenCV can not be found by CMake. If I do `ccmake` instead of `cmake`, I can see the following set variable: `OpenCV_DIR=/usr/local/share/OpenCV`. How does it look on your machine?

And since this has nothing to do with this repo, it would be nice if we could go on in https://github.com/VLOGroup/imageutilities/issues/5 and close this issue here.

**Comment by raymond00000** [comment]
ok, so i will use 16.04
for OpenCV, which version you are using? I found that if I use OpenCV3.1, I have to choose a branch that support cuda 8.0? 

You are using CUDA 8? or 7.5?

Many thanks for advice. I really have to make this works!! thanks.

**Comment by reini1305** [comment]
I'm using a self-compiled version of Opencv 3.2 and CUDA 8 on Ubuntu 16.04.

**Comment by raymond00000** [comment]
OK, for opencv 3.2, 

I will refer to this guide:
http://docs.opencv.org/trunk/d7/d9f/tutorial_linux_install.html

I will run this to cmake. 
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local .. -D BUILD_SHARED_LIBS=ON


Do you foresee that above steps will lead a failure? 
Thank a lot.

**Comment by reini1305** [comment]
This should work, I also built it with default parameters.

**Comment by raymond00000** [comment]
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local .. -D BUILD_SHARED_LIBS=ON

better to add this too?
-D BUILD_SHARED_LIBS=ON

thanks.

**Comment by reini1305** [comment]
Yes, if it is not enabled by default.

**Comment by raymond00000** [comment]
ok, i will try from scratch and let me know the result, thank a lot.

**Comment by raymond00000** [comment]
16.04.2-desktop-amd64.iso , you are using 16.04.2?

**Comment by reini1305** [comment]
14.04 but 16.04 will be fine

**Comment by raymond00000** [comment]
i am still installing new OS

my ccmake returned this,  IU_USE_GUI  is OFF ...

CMAKE_BUILD_TYPE                                                              
 CMAKE_INSTALL_PREFIX             /usr/local                                   
 CUDA_HOST_COMPILER               /usr/bin/cc                                  
 CUDA_SDK_ROOT_DIR                CUDA_SDK_ROOT_DIR-NOTFOUND                   
 CUDA_TOOLKIT_ROOT_DIR            /usr/local/cuda                              
 CUDA_USE_STATIC_CUDA_RUNTIME     ON                                           
 CUDA_rt_LIBRARY                  /usr/lib/x86_64-linux-gnu/librt.so           
 Eigen3_DIR                       Eigen3_DIR-NOTFOUND                          
 IU_BUILD_STATIC                  OFF                                          
 IU_INSTALL_LOCAL                 ON                                           
 IU_USE_GUI                       OFF                                          
 IU_USE_IO                        ON                                           
 IU_USE_MATH                      ON                                           
 IU_USE_NDARRAY                   ON                                           
 OpenCV_DIR                       /usr/local/share/OpenCV                      
 Qt5Core_DIR                      Qt5Core_DIR-NOTFOUND                         
 Qt5OpenGL_DIR                    Qt5OpenGL_DIR-NOTFOUND 

wait, let me update something, 
CUDA_SDK_ROOT_DIR..

**Comment by raymond00000** [comment]
export IMAGEUTILITIES_ROOT=~/dvs/dvs-reconstruction/imageutilities
export CUDA_SDK_ROOT_DIR=/usr/local/cuda/samples
export OpenCV_DIR=/usr/local/share/OpenCV

~/dvs/dvs-reconstruction/imageutilities/build$ ccmake .
ccmake .

 CMAKE_BUILD_TYPE                                                              
 CMAKE_INSTALL_PREFIX             /home/lscm/dvs/dvs-reconstruction/imageutilit
 CUDA_HOST_COMPILER               /usr/bin/cc                                  
 CUDA_SDK_ROOT_DIR                CUDA_SDK_ROOT_DIR-NOTFOUND                   
 CUDA_TOOLKIT_ROOT_DIR            /usr/local/cuda                              
 CUDA_USE_STATIC_CUDA_RUNTIME     ON                                           
 CUDA_rt_LIBRARY                  /usr/lib/x86_64-linux-gnu/librt.so           
 Eigen3_DIR                       Eigen3_DIR-NOTFOUND                          
 IU_BUILD_STATIC                  OFF                                          
 IU_INSTALL_LOCAL                 ON                                           
 IU_USE_GUI                       OFF                                          
 IU_USE_IO                        ON                                           
 IU_USE_MATH                      ON                                           
 IU_USE_NDARRAY                   ON                                           
 OpenCV_DIR                       /usr/local/share/OpenCV                      
 Qt5Core_DIR                      Qt5Core_DIR-NOTFOUND                         
 Qt5OpenGL_DIR                    Qt5OpenGL_DIR-NOTFOUND  


but i got this:

:/usr/local/cuda/samples$ ls
0_Simple     2_Graphics  4_Finance      6_Advanced       common    Makefile
1_Utilities  3_Imaging   5_Simulations  7_CUDALibraries  EULA.txt

but i still got:
 CUDA_SDK_ROOT_DIR                CUDA_SDK_ROOT_DIR-NOTFOUND

**Comment by reini1305** [comment]
Please set `CUDA_SDK_ROOT_DIR` directly within `ccmake`

**Comment by raymond00000** [comment]
yes, i now tried to set CUDA_SDK_ROOT_DIR directly , and IU_USE_GUI ON directly, hope I can build it, I am really appreciated for your advice! many thanks.

**Comment by raymond00000** [comment]
seems like i cannot change IU_USE_GUI ON as "generate" set it back to off..

**Comment by reini1305** [comment]
This means that either QT5 or OpenCV have not been found.

**Comment by reini1305** [comment]
Let me move this thread to https://github.com/VLOGroup/imageutilities/issues/5
