### ISSUE TITLE
meaning of the event/image on the UI?

### ISSUE THREAD

**Issue by raymond00000** [VLOGroup/dvs-reconstruction#6]
I can open the saved data like this:

20.0405 32 115 -1
20.0405 32 115 -1
20.0405 32 114 -1
20.0405 33 115 -1
20.0406 25 113 -1
20.0406 23 121 1
20.0406 15 115 1
20.0406 16 113 1
20.0406 15 114 1
20.0406 17 119 1

is that a good way to isolate the data sequence when an object is seen by the cam?

I wonder if the event/image = 1000 means a moving average of 1000 to build the reconstruction image?

thanks.

**Comment by reini1305** [comment]
I'm not sure if I get your first question completely. The meaning of events/image is the same as in section 4.1 in the paper (https://arxiv.org/abs/1607.06283). So this is the information that is used to create a new output image.
