### ISSUE TITLE
Problem launching live_reconstruction_gui

### ISSUE THREAD

**Issue by alirezadir** [VLOGroup/dvs-reconstruction#7]
Hi, I was able to compile, but when I try running `live_reconstruction_gui`, it throws `Segmentation fault (core dumped) error`. I appreciate if you could help. Thanks.

**Comment by reini1305** [comment]
Hi! Can you get me more information? Maybe by trying to look at a stack trace or changing the `CMAKE_BUILD_TYPE` to `Debug` and then running it through a `gdb`?
