### ISSUE TITLE
Unable to launch live_reconstruction_gui

### ISSUE THREAD

**Issue by ghost** [VLOGroup/dvs-reconstruction#8]
Hi,
I build and install all dependencies and finally build src as well, according to the README. But I am unable to launch the live_reconstruction_gui. It shows the following error: 

QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QOpenGLWidget: Failed to create context
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QOpenGLWidget: Failed to create context
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QOpenGLWidget: Failed to create context
composeAndFlush: makeCurrent() failed

What am I missing? Could you help me resolve this issue? Thanks

**Comment by reini1305** [comment]
Hi!

Did you install your graphics driver correctly? Does any other OpenGL application work? Maybe try again to run as root...
What is your operating system / graphics card / nvidia driver?

**Comment by ghost** [comment]
Hi,

Other OpenGL are working fine, and the graphics driver is installed correctly too. We use NVIDIA Titan X on Ubuntu 14.04, and we've used them for training deep neural nets. Running it as root gave the same error. I'm using Qt version 5.6

**Comment by reini1305** [comment]
OK, this is weird. The one difference to your setup is, that I've always used Ubuntu 16.04.

**Comment by ghost** [comment]
We are working on the same problem and wanted to compare results. Would it be possible to provide code for your method which can produce intensity images by taking event data as input, without using the GUI? Thanks

**Comment by reini1305** [comment]
Added an offline evaluation script. Might be rough around the edges but should produce the same results as in the paper.
