### ISSUE TITLE
Building with the WITH_DAVIS set to ON still gives 128*128

### ISSUE THREAD

**Issue by smmmmi** [VLOGroup/dvs-reconstruction#9]
Hi, after building with the WITH_DAVIS set to ON, I tested offline on a small sequence but the output is 128x128 instead of 240x180.

**Comment by reini1305** [comment]
I'm not sure what you mean by "offline", but the WITH_DAVIS flag only affects the live mode of the GUI application. The provided sample data is from a DVS128 camera.

**Comment by smmmmi** [comment]
Thanks for the reply, I mean the offline_reconstruction using downloaded datasets from the DAVIS camera. Any clue how to make that possible?

**Comment by reini1305** [comment]
It's a long time for me since touching this code :)

There are actually width and height parameters for the command line which you can set accordingly. So the WITH_DAVIS flag has no effect for this executable.
